### ISSUE TITLE
Probleme nom de serveur

### ISSUE THREAD

**Issue by thedourn** [MvWild/ImportHome#1]
Est qu'il serai possible de choisir le nom du serveur à rentré dans la colonne de la bdd server ?

Car pour le moment les home sont rentré dans la en tramps que survie alors que c'est survie1

**Comment by Fonkio** [comment]
Le script demande déjà le nom du serveur ? je comprend pas la question du coup

**Comment by Fonkio** [comment]
C'est déjà fait du coup
