### ISSUE TITLE
Import des home netherwild

### ISSUE THREAD

**Issue by thedourn** [MvWild/ImportHome#3]
Ne pas importer les homes du netherwild dans le serveur survie mais dans server NetherWild et world NetherWild

**Comment by Fonkio** [comment]
Avec la fonction que j'ai ajouté pour #2 tu pourras faire ça sans problème en ignorant les autres mondes mais en plusieurs fois du coup (un import pour les homes de survie, un import pour les homes du nether, ... avec le ignore other world activé)
